version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: golangulator_postgres
    restart: always
    environment:
      POSTGRES_USER: golangulator
      POSTGRES_PASSWORD: golangulator_password
      POSTGRES_DB: golangulator
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
